### ISSUE TITLE
Login error - unable to login to scatter

### ISSUE THREAD

**Issue by sun1211** [EOSIO/ual-plainjs-renderer#27] opened 2019-04-03 15:28 UTC
**yarn build -w**

[10:03:32 PM] Starting compilation in watch mode...

[10:03:35 PM] Found 0 errors. Watching for file changes.

**yarn example**
`yarn run v1.15.2
$ yarn build && mkdir dist/public && webpack --config webpack.config.js && nodemon server --exec babel-node -e js
$ yarn clean && tsc --build tsconfig.json
$ rm -rf dist
Hash: be89f3127d52e718d7bc
Version: webpack 4.29.3
Time: 3103ms
Built at: 04/03/2019 10:04:05 PM
         Asset       Size  Chunks             Chunk Names
    index.html  632 bytes          [emitted]  
main_bundle.js   1.55 MiB    main  [emitted]  main
Entrypoint main = main_bundle.js
[0] multi ./dist/examples/src/ButtonWebView.js 28 bytes {main} [built]
[1] crypto (ignored) 15 bytes {main} [built]
[2] util (ignored) 15 bytes {main} [built]
[3] util (ignored) 15 bytes {main} [built]
[../dist/UALJs.js] 10.2 KiB {main} [built]
[../dist/UALJsAbstractBaseComponent.js] 2.49 KiB {main} [built]
[../dist/UALJsDom.js] 33.9 KiB {main} [built]
[../dist/index.js] 376 bytes {main} [built]
[./dist/examples/src/AuthMocks.js] 3.83 KiB {main} [built]
[./dist/examples/src/ButtonWebView.js] 3.76 KiB {main} [built]
[./dist/examples/src/demo-transaction.js] 489 bytes {main} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {main} [built]
    + 501 hidden modules
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./server/template.html] 790 bytes {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
        + 1 hidden module
[nodemon] 1.18.10
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node server`
Development server is up and running on port 3000
`

But when I click Login to scatter 

![image](https://user-images.githubusercontent.com/16816204/55491590-f2638100-565f-11e9-81e2-534324509151.png)

**Comment by jeffreyssmith2nd** [comment] 2019-04-30 20:08
Double check that you have setup the `.env` as suggested in the examples README. A misconfigured chain_id or endpoint can be the cause of this.

**Comment by chris-allnutt** [comment] 2019-07-29 18:54
@sun1211 closing this PR as we've received no updates.  If you are still having problems please open a new ticket.

**Closed by chris-allnutt** 2019-07-29 18:54 UTC
Labels: bug
